## Backpropagation Algorithm - Regression

epochs=5

    for i in range (epochs):
        for j in range (X.shape[0]):
            Select 1 row ( random)
            Predict (using forward propogation)
            Calculate Loss (using Loss Function - MSE)
            Update weights and Bias using GD
        
        Calculate average loss for the epochs

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.get_weights()

[array([[ 0.4688815 , -0.6643269 ],
        [-0.76427245,  0.42382097]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0168453],
        [ 0.0567317]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
new_weights = [np.array([[0.1 , 0.1],
                [0.1 , 0.1]], dtype=np.float32),
                np.array([0., 0.], dtype=np.float32),
                np.array([[0.1], 
                        [0.1]],dtype = np.float32),
                np.array([0.], dtype=np.float32)]

In [19]:
model.set_weights(new_weights)

In [21]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

model.fit(df.iloc